apiVersion: v1
kind: Secret
metadata:
  name: flask-portfolio-secrets
  namespace: flask-portfolio
type: Opaque
stringData:
  SECRET_KEY: "6n4N5MrLi6zNDE2FaNZ75FR0tgxvKNxWXRCK44ojBPyGGg2sQTzjJQQJ99CEACqBBLyEqg7NAAACAZCR50xT"
  # Add other secrets here if needed
