apiVersion: v1
kind: Service
metadata:
  name: flask-portfolio-service
  namespace: flask-portfolio
  labels:
    app: flask-portfolio
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5004
    protocol: TCP
    name: http
  selector:
    app: flask-portfolio
